// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
import { products } from "npm:@/data/products";
var list_products_default = defineTool({
  name: "list_products",
  title: "Listar productos",
  description: "Lista todos los productos del cat\xE1logo AIT (opcionalmente filtrados por categor\xEDa o marca).",
  inputSchema: {
    category: z.string().optional().describe("Categor\xEDa: PLC, V\xE1lvulas, Transmisores, HMI, etc."),
    brand: z.string().optional().describe("Marca: Siemens, Fisher, Rosemount, Allen-Bradley, etc.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, brand }) => {
    const list = products.filter(
      (p) => (!category || p.category.toLowerCase().includes(category.toLowerCase())) && (!brand || p.brand.toLowerCase().includes(brand.toLowerCase()))
    );
    return {
      content: [{ type: "text", text: JSON.stringify(list.map(({ id, name, brand: brand2, sku, price, category: category2 }) => ({ id, name, brand: brand2, sku, price, category: category2 })), null, 2) }]
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { products as products2 } from "npm:@/data/products";
var search_products_default = defineTool2({
  name: "search_products",
  title: "Buscar productos",
  description: "Busca productos por texto libre (nombre, marca, SKU o descripci\xF3n).",
  inputSchema: { query: z2.string().min(1).describe("Texto de b\xFAsqueda") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query.toLowerCase();
    const hits = products2.filter(
      (p) => p.name.toLowerCase().includes(q) || p.brand.toLowerCase().includes(q) || p.sku.toLowerCase().includes(q) || p.description.toLowerCase().includes(q)
    );
    return { content: [{ type: "text", text: JSON.stringify(hits, null, 2) }] };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { products as products3 } from "npm:@/data/products";
var get_product_default = defineTool3({
  name: "get_product",
  title: "Detalle de producto",
  description: "Obtiene el detalle completo de un producto por ID o SKU.",
  inputSchema: { idOrSku: z3.string().min(1) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ idOrSku }) => {
    const p = products3.find(
      (x) => x.id === idOrSku || x.sku.toLowerCase() === idOrSku.toLowerCase()
    );
    if (!p) return { content: [{ type: "text", text: "No encontrado" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(p, null, 2) }] };
  }
});

// src/lib/mcp/tools/list-my-quote.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.7";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function getOrCreateDraft(ctx) {
  const sb = supabaseForUser(ctx);
  const userId = ctx.getUserId();
  const { data: existing } = await sb.from("quotes").select("id").eq("user_id", userId).eq("status", "draft").maybeSingle();
  if (existing) return { sb, quoteId: existing.id, userId };
  const { data: created, error } = await sb.from("quotes").insert({ user_id: userId, status: "draft" }).select("id").single();
  if (error) throw error;
  return { sb, quoteId: created.id, userId };
}

// src/lib/mcp/tools/list-my-quote.ts
var list_my_quote_default = defineTool4({
  name: "list_my_quote",
  title: "Ver mi cotizaci\xF3n",
  description: "Lista los \xEDtems actuales del carrito de cotizaci\xF3n del usuario autenticado.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("quotes").select("id,status,created_at,quote_items(id,sku,name,brand,price,qty)").eq("user_id", ctx.getUserId()).eq("status", "draft").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? { items: [] }, null, 2) }] };
  }
});

// src/lib/mcp/tools/add-to-quote.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
import { products as products4 } from "npm:@/data/products";
var add_to_quote_default = defineTool5({
  name: "add_to_my_quote",
  title: "Agregar a mi cotizaci\xF3n",
  description: "Agrega un producto (por ID o SKU) a la cotizaci\xF3n del usuario autenticado.",
  inputSchema: {
    idOrSku: z4.string().min(1),
    qty: z4.number().int().min(1).max(999).default(1)
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ idOrSku, qty }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const p = products4.find((x) => x.id === idOrSku || x.sku.toLowerCase() === idOrSku.toLowerCase());
    if (!p) return { content: [{ type: "text", text: "Producto no encontrado" }], isError: true };
    const { sb, quoteId, userId } = await getOrCreateDraft(ctx);
    const { data: existing } = await sb.from("quote_items").select("id,qty").eq("quote_id", quoteId).eq("sku", p.sku).maybeSingle();
    if (existing) {
      const newQty = Math.min(999, existing.qty + qty);
      const { error } = await sb.from("quote_items").update({ qty: newQty }).eq("id", existing.id);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    } else {
      const { error } = await sb.from("quote_items").insert({
        quote_id: quoteId,
        user_id: userId,
        sku: p.sku,
        name: p.name,
        brand: p.brand,
        price: p.price,
        qty,
        image: p.image
      });
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return { content: [{ type: "text", text: `Agregado: ${qty} \xD7 ${p.name} (${p.sku})` }] };
  }
});

// src/lib/mcp/tools/remove-from-quote.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
var remove_from_quote_default = defineTool6({
  name: "remove_from_my_quote",
  title: "Quitar de mi cotizaci\xF3n",
  description: "Elimina un \xEDtem (por SKU) de la cotizaci\xF3n draft del usuario.",
  inputSchema: { sku: z5.string().min(1) },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ sku }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data: q } = await sb.from("quotes").select("id").eq("user_id", ctx.getUserId()).eq("status", "draft").maybeSingle();
    if (!q) return { content: [{ type: "text", text: "No hay cotizaci\xF3n activa" }] };
    const { error } = await sb.from("quote_items").delete().eq("quote_id", q.id).eq("sku", sku);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Eliminado ${sku}` }] };
  }
});

// src/lib/mcp/tools/submit-quote.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.25.76";
var submit_quote_default = defineTool7({
  name: "submit_my_quote",
  title: "Enviar cotizaci\xF3n",
  description: "Marca la cotizaci\xF3n draft actual como enviada. Un asesor de AIT contactar\xE1 al usuario.",
  inputSchema: { notes: z6.string().max(2e3).optional() },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ notes }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data: q } = await sb.from("quotes").select("id, quote_items(id)").eq("user_id", ctx.getUserId()).eq("status", "draft").maybeSingle();
    if (!q || !q.quote_items?.length)
      return { content: [{ type: "text", text: "La cotizaci\xF3n est\xE1 vac\xEDa" }], isError: true };
    const { error } = await sb.from("quotes").update({ status: "submitted", submitted_at: (/* @__PURE__ */ new Date()).toISOString(), notes: notes ?? null }).eq("id", q.id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: "Cotizaci\xF3n enviada. Un asesor te contactar\xE1 pronto." }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bqzhtncdlnjdyjjojxrt";
var mcp_default = defineMcp({
  name: "ait-ventas-mcp",
  title: "AIT Ventas Industriales",
  version: "0.1.0",
  instructions: "Herramientas de la tienda AIT Soluciones Autom\xE1ticas. Permite consultar el cat\xE1logo industrial (v\xE1lvulas, PLC, transmisores, HMI) y gestionar la cotizaci\xF3n personal del usuario autenticado (agregar productos, revisar, enviar).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_products_default,
    search_products_default,
    get_product_default,
    list_my_quote_default,
    add_to_quote_default,
    remove_from_quote_default,
    submit_quote_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
